version: "3"

services:
  db: 
    container_name: savify-database
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - savify

  mailcatcher:
    container_name: savify-mails
    build:
      context: .docker/mailcatcher
    restart: always
    ports:
      - "1025:1025"
      - "8888:80"

volumes: 
  database_data:

networks:
  savify:
    name: savify
