name: CI

on:
  push:
    branches: ["main"]

  pull_request:

jobs:
  codestyle:
    name: CodeStyle
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Code style verifying
        run: dotnet format --verify-no-changes --verbosity=detailed

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: codestyle

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: .

  arch-tests:
    name: Architectural Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal --filter TestCategory=ArchTest

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .

      - name: Build
        run: dotnet build

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal --filter TestCategory=UnitTest --collect:"XPlat Code Coverage" --results-directory TestReports

      - name: Upload Test Coverage Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-reports
          path: TestReports

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .

      - name: Run Tests
        run: dotnet test --no-build -v normal -e ASPNETCORE_ENVIRONMENT=Testing --filter TestCategory=IntegrationTest --collect:"XPlat Code Coverage" --results-directory TestReports

      - name: Upload Test Coverage Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: integration-tests-reports
          path: TestReports

  modules-integration-tests:
    name: Modules Integration Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .

      - name: Run Tests
        run: dotnet test --no-build -v normal -e ASPNETCORE_ENVIRONMENT=Testing --filter TestCategory=ModulesIntegrationTest --collect:"XPlat Code Coverage" --results-directory TestReports

      - name: Upload Test Coverage Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: modules-integration-tests-reports
          path: TestReports

  code-coverage-report:
    name: Code Coverage
    runs-on: ubuntu-latest
    needs:
      - unit-tests
      - integration-tests
      - modules-integration-tests

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Download Unit Tests Reports
        uses: actions/download-artifact@v4
        with:
          name: unit-tests-reports
          path: UnitTestReports

      - name: Download Integration Tests Reports
        uses: actions/download-artifact@v4
        with:
          name: integration-tests-reports
          path: IntegrationTestReports

      - name: Download Modules Integration Tests Reports
        uses: actions/download-artifact@v4
        with:
          name: modules-integration-tests-reports
          path: ModulesIntegrationTestReports

      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
        with:
          reports: 'UnitTestReports/*/coverage.cobertura.xml;IntegrationTestReports/*/coverage.cobertura.xml;ModulesIntegrationTestReports/*/coverage.cobertura.xml'
          targetdir: 'coverage'
          reporttypes: 'Html;Badges'
          toolpath: 'reportgeneratortool'

      - name: Upload Coverage Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReport
          path: coverage
